# Generated by Django 3.2.5 on 2021-07-18 07:59

from django.db import migrations, models
import django.db.models.deletion
import portfolio.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photoshoots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(max_length=50, verbose_name='тег <alt>')),
                ('image', models.ImageField(upload_to=portfolio.models.generate_path)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='photoshoots.album')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя категории')),
                ('list_of_image', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='photoshoots.album')),
                ('main_image', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='portfolio.image')),
            ],
        ),
    ]
