# Generated by Django 3.2.5 on 2021-07-21 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photoshoots', '0004_auto_20210721_1819'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='choosen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photoshoots.album'),
        ),
    ]
