# Generated by Django 3.2.5 on 2021-07-21 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210721_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='choosen',
        ),
    ]
