# Generated by Django 3.2.5 on 2021-07-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_image_choosen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='alt',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='тег <alt>'),
        ),
    ]
