# Generated by Django 3.2.5 on 2021-07-04 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='photo_shoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название фотосессии')),
                ('state', models.IntegerField(choices=[(6, 'Создание мудборда'), (5, 'Съемка назачена'), (4, 'Отбор'), (3, 'Обработка'), (2, 'Завершено'), (1, 'Отправлено')], default=6, verbose_name='Статус')),
                ('date', models.DateField(verbose_name='Дата съемки')),
                ('link_to_pinterest', models.URLField(verbose_name='Ссылка на доску в Pinterest')),
                ('result_link', models.URLField(verbose_name='Ссылка на результат')),
                ('num_choose', models.IntegerField(default=10, verbose_name='Колличество снимков, котороые нужно выбрать')),
                ('choosen', models.BooleanField(help_text='Отметить, когда клиент уже отобрал снимки', verbose_name='Снимки уже выбраны')),
                ('linkUser', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
