# Generated by Django 3.2.5 on 2021-07-18 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photoshoots', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo_shoot',
            name='linkUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='user.myuser'),
        ),
    ]
