# Generated by Django 3.2.5 on 2021-07-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoshoots', '0003_auto_20210718_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo_shoot',
            name='chosen',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo_shoot',
            name='moodboard',
            field=models.FileField(blank=True, null=True, upload_to='moodboard', verbose_name='Мудборд'),
        ),
    ]
