# Generated by Django 3.2.5 on 2021-07-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoshoots', '0006_alter_photo_shoot_chosen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo_shoot',
            name='chosen',
            field=models.JSONField(default=list),
        ),
    ]
