# Generated by Django 3.2.5 on 2021-07-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoshoots', '0007_alter_photo_shoot_chosen'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo_shoot',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='photo_shoot',
            name='chosen',
            field=models.JSONField(default=list, verbose_name='Выбранные фото'),
        ),
    ]
