# Generated by Django 3.2.5 on 2021-07-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoshoots', '0008_auto_20210723_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo_shoot',
            name='chosen',
            field=models.JSONField(blank=True, default=list, verbose_name='Выбранные фото'),
        ),
    ]
