# Generated by Django 3.2.5 on 2021-07-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoshoots', '0009_alter_photo_shoot_chosen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField(default=False)),
                ('what_liked', models.TextField(blank=True, null=True, verbose_name='Что вам не очень понравилось? (организация, долго время ожидания фото)')),
                ('what_disliked', models.TextField(blank=True, null=True, verbose_name='Что вам вам понравилось?')),
                ('post_photo_in_social', models.BooleanField(blank=True, null=True, verbose_name='Вылоижили ли фото в какие-либо социальные сети?')),
                ('rate_mood', models.IntegerField(blank=True, null=True, verbose_name='Оцените ваше общее впечаталение после съемки (от 1 до 5)')),
                ('rate_photo', models.IntegerField(blank=True, null=True, verbose_name='Оцените ваше общее впечатление от фото (от 1 до 5)')),
            ],
        ),
    ]
