# Generated by Django 3.2.5 on 2021-07-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoshoots', '0010_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rate_mood',
            field=models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], null=True, verbose_name='Оцените ваше общее впечаталение после съемки (от 1 до 5)'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rate_photo',
            field=models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], null=True, verbose_name='Оцените ваше общее впечатление от фото (от 1 до 5)'),
        ),
    ]
