# Generated by Django 3.2.5 on 2021-07-29 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photoshoots', '0011_auto_20210728_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='passed',
        ),
        migrations.AddField(
            model_name='review',
            name='photo_shoot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='photoshoots.photo_shoot'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='post_photo_in_social',
            field=models.BooleanField(blank=True, null=True, verbose_name='Выложили ли фото в какие-либо социальные сети?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rate_mood',
            field=models.IntegerField(blank=True, null=True, verbose_name='Оцените ваше общее впечаталение после съемки (от 1 до 5)'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rate_photo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Оцените ваше общее впечатление от фото (от 1 до 5)'),
        ),
    ]
